### ISSUE TITLE
Update version to include "Remove test-code" commit

### ISSUE THREAD

**Issue by thcolin** [mattiash/randomized-interval#1]
Hello !

I'm currently using your lib for one of my project and I got some unexpected `console.log`, I see you got a commit which remove test code : [d76a5ecc0f6a61b69815e747c49159faeeca50ad](https://github.com/mattiash/randomized-interval/commit/d76a5ecc0f6a61b69815e747c49159faeeca50ad), the problem is it's unavailable on `npm` unless you bump a new version, so could you release a `1.0.3` with last commit if no problem for you please ?

Thanks !

**Comment by mattiash** [comment]
I just released 1.0.3 on npm.
